spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/notidb
    username: admin
    password: noti
    driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug



